[tool.poetry]
name = "cse571-asu"
version = "0.1.0"
description = ""
authors = ["Sangjoon Han <jphan32@me.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
